name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "master"
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@mattcarpenter.net"
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          maven-args: "-Dmaven.javadoc.skip=true"
